[package]
name = "js8-reach"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "web"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
env_logger = "0.10.0"
log = "0.4.17"
rocket = "0.5.0-rc.3"
rumqttc = "0.20.0"
serde = "1.0.160"
